name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    # (Optionnel) Ajouter des tests ici
    # - name: Run tests
    #   run: npm test

    - name: Sync files with rsync
      uses: burnett01/rsync-deployments@5.2.3
      with:
        switches: -avzr --delete --exclude={'node_modules/','.env','.git'}
        path: ./
        remote_path: /opt/backend/
        remote_host: ${{ secrets.EC2_HOST }}
        remote_user: ${{ secrets.EC2_USER }}
        remote_key: ${{ secrets.EC2_SSH_KEY }}

    - name: Restart PM2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /opt/backend
          npm install --production
          pm2 reload ecosystem.config.js --env production
          pm2 save