name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # (Optionnel) Étape de build ou de tests
      # - name: Build project
      #   run: npm install && npm run build

      # Étape 2 : Copier les fichiers sur le serveur
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./"           # Ajustez ce chemin selon ce que vous souhaitez déployer (par exemple, le dossier build/dist)
          target: "/opt/backend"  # Chemin sur le serveur où déposer les fichiers