name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    # (Optionnel) Ajouter des tests ici
    # - name: Run tests
    #   run: npm test

    - name: Add remote host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          rsync -avz --delete -e "ssh -i /home/deployer/.ssh/github_actions" \
            --exclude='node_modules' \
            --exclude='.git' \
            $GITHUB_WORKSPACE/ deployer@${{ secrets.EC2_HOST }}:/opt/backend/

    - name: Restart PM2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /opt/backend
          npm install --production
          pm2 reload ecosystem.config.js --env production
          pm2 save